/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as PrivateRouteRouteImport } from './routes/_private/route'
import { Route as PrivateIndexRouteImport } from './routes/_private/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as PrivateProfileRouteImport } from './routes/_private/profile'
import { Route as PrivateEventsIndexRouteImport } from './routes/_private/events/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PrivateEventsNewRouteImport } from './routes/_private/events/new'
import { Route as PrivateEventsIdRouteRouteImport } from './routes/_private/events/$id/route'
import { Route as PrivateEventsIdIndexRouteImport } from './routes/_private/events/$id/index'
import { Route as PrivateEventsIdEditRouteImport } from './routes/_private/events/$id/edit'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const PrivateProfileRoute = PrivateProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateEventsIndexRoute = PrivateEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateEventsNewRoute = PrivateEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateEventsIdRouteRoute = PrivateEventsIdRouteRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateEventsIdIndexRoute = PrivateEventsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateEventsIdRouteRoute,
} as any)
const PrivateEventsIdEditRoute = PrivateEventsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PrivateEventsIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PrivateIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/profile': typeof PrivateProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/events/$id': typeof PrivateEventsIdRouteRouteWithChildren
  '/events/new': typeof PrivateEventsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/events/': typeof PrivateEventsIndexRoute
  '/events/$id/edit': typeof PrivateEventsIdEditRoute
  '/events/$id/': typeof PrivateEventsIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/profile': typeof PrivateProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof PrivateIndexRoute
  '/events/new': typeof PrivateEventsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/events': typeof PrivateEventsIndexRoute
  '/events/$id/edit': typeof PrivateEventsIdEditRoute
  '/events/$id': typeof PrivateEventsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/_private/profile': typeof PrivateProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_private/': typeof PrivateIndexRoute
  '/_private/events/$id': typeof PrivateEventsIdRouteRouteWithChildren
  '/_private/events/new': typeof PrivateEventsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_private/events/': typeof PrivateEventsIndexRoute
  '/_private/events/$id/edit': typeof PrivateEventsIdEditRoute
  '/_private/events/$id/': typeof PrivateEventsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/profile'
    | '/auth/login'
    | '/auth/register'
    | '/events/$id'
    | '/events/new'
    | '/api/auth/$'
    | '/events/'
    | '/events/$id/edit'
    | '/events/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/profile'
    | '/auth/login'
    | '/auth/register'
    | '/'
    | '/events/new'
    | '/api/auth/$'
    | '/events'
    | '/events/$id/edit'
    | '/events/$id'
  id:
    | '__root__'
    | '/_private'
    | '/auth'
    | '/_private/profile'
    | '/auth/login'
    | '/auth/register'
    | '/_private/'
    | '/_private/events/$id'
    | '/_private/events/new'
    | '/api/auth/$'
    | '/_private/events/'
    | '/_private/events/$id/edit'
    | '/_private/events/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/': {
      id: '/_private/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_private/profile': {
      id: '/_private/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PrivateProfileRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/events/': {
      id: '/_private/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof PrivateEventsIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/events/new': {
      id: '/_private/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof PrivateEventsNewRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/events/$id': {
      id: '/_private/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof PrivateEventsIdRouteRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/events/$id/': {
      id: '/_private/events/$id/'
      path: '/'
      fullPath: '/events/$id/'
      preLoaderRoute: typeof PrivateEventsIdIndexRouteImport
      parentRoute: typeof PrivateEventsIdRouteRoute
    }
    '/_private/events/$id/edit': {
      id: '/_private/events/$id/edit'
      path: '/edit'
      fullPath: '/events/$id/edit'
      preLoaderRoute: typeof PrivateEventsIdEditRouteImport
      parentRoute: typeof PrivateEventsIdRouteRoute
    }
  }
}

interface PrivateEventsIdRouteRouteChildren {
  PrivateEventsIdEditRoute: typeof PrivateEventsIdEditRoute
  PrivateEventsIdIndexRoute: typeof PrivateEventsIdIndexRoute
}

const PrivateEventsIdRouteRouteChildren: PrivateEventsIdRouteRouteChildren = {
  PrivateEventsIdEditRoute: PrivateEventsIdEditRoute,
  PrivateEventsIdIndexRoute: PrivateEventsIdIndexRoute,
}

const PrivateEventsIdRouteRouteWithChildren =
  PrivateEventsIdRouteRoute._addFileChildren(PrivateEventsIdRouteRouteChildren)

interface PrivateRouteRouteChildren {
  PrivateProfileRoute: typeof PrivateProfileRoute
  PrivateIndexRoute: typeof PrivateIndexRoute
  PrivateEventsIdRouteRoute: typeof PrivateEventsIdRouteRouteWithChildren
  PrivateEventsNewRoute: typeof PrivateEventsNewRoute
  PrivateEventsIndexRoute: typeof PrivateEventsIndexRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateProfileRoute: PrivateProfileRoute,
  PrivateIndexRoute: PrivateIndexRoute,
  PrivateEventsIdRouteRoute: PrivateEventsIdRouteRouteWithChildren,
  PrivateEventsNewRoute: PrivateEventsNewRoute,
  PrivateEventsIndexRoute: PrivateEventsIndexRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
